import { createWriteStream, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";
import { pipeline } from "node:stream/promises";

const manifestPath = process.argv[2] ?? "asset-sources.json";
const root = process.cwd();
const jacketDir = join(root, "public", "assets", "jackets");
const previewDir = join(root, "public", "assets", "previews");
const overridePath = join(root, "src", "data", "assetOverrides.ts");

if (!existsSync(manifestPath)) {
  console.error(`Missing ${manifestPath}. Copy asset-sources.example.json to asset-sources.json first.`);
  process.exit(1);
}

mkdirSync(jacketDir, { recursive: true });
mkdirSync(previewDir, { recursive: true });

const sources = JSON.parse(readFileSync(manifestPath, "utf8"));

if (!Array.isArray(sources)) {
  console.error("Asset manifest must be an array.");
  process.exit(1);
}

const overrides = {};

for (const source of sources) {
  validateSource(source);

  const override = {};

  if (source.jacketUrl) {
    const ext = getSafeExtension(source.jacketUrl, ".webp");
    const assetPath = `/assets/jackets/${source.songId}${ext}`;
    await download(source.jacketUrl, join(jacketDir, `${source.songId}${ext}`), "image/");
    override.jacket = assetPath;
  }

  if (source.previewUrl) {
    const ext = getSafeExtension(source.previewUrl, ".mp3");
    const assetPath = `/assets/previews/${source.songId}${ext}`;
    await download(source.previewUrl, join(previewDir, `${source.songId}${ext}`), "audio/");
    override.previewAudio = assetPath;
  }

  overrides[source.songId] = override;
}

writeFileSync(
  overridePath,
  `interface AssetOverride {
  jacket?: string;
  previewAudio?: string;
}

// Generated by npm run assets:import.
// Keep license/source notes in ${manifestPath}; only import assets you are allowed to publish.
export const assetOverrides: Record<string, AssetOverride> = ${JSON.stringify(overrides, null, 2)};
`,
  "utf8"
);

console.log(`Imported ${Object.keys(overrides).length} asset override(s).`);

function validateSource(source) {
  if (!source || typeof source !== "object") {
    throw new Error("Each source must be an object.");
  }

  if (!source.songId || typeof source.songId !== "string") {
    throw new Error("Each source needs a string songId.");
  }

  if (!source.licenseNote || typeof source.licenseNote !== "string" || source.licenseNote.length < 12) {
    throw new Error(`${source.songId} needs a licenseNote/source note before importing.`);
  }
}

async function download(url, destination, contentTypePrefix) {
  const response = await fetch(url, {
    headers: {
      "user-agent": "maimai-music-cup-asset-importer/0.1"
    }
  });

  if (!response.ok || !response.body) {
    throw new Error(`Failed to download ${url}: ${response.status} ${response.statusText}`);
  }

  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.startsWith(contentTypePrefix)) {
    throw new Error(`Unexpected content type for ${url}: ${contentType || "unknown"}`);
  }

  await pipeline(response.body, createWriteStream(destination));
  console.log(`Saved ${destination}`);
}

function getSafeExtension(url, fallback) {
  const pathname = new URL(url).pathname;
  const ext = extname(pathname).toLowerCase();
  const allowed = new Set([".png", ".jpg", ".jpeg", ".webp", ".mp3", ".m4a", ".aac", ".ogg"]);
  return allowed.has(ext) ? ext : fallback;
}
